# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap, QFont, QFontDatabase, QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 504)
        MainWindow.setWindowIcon(QIcon('resource/clean.png'))

        # 加载字体文件
        font_id = QFontDatabase.addApplicationFont("font/DingTalk_JinBuTi_Regular.ttf")
        # 获取字体家族名称
        font_families = QFontDatabase.applicationFontFamilies(font_id)
        font_family = font_families[0]
        # 创建字体对象
        self.font = QFont(font_family)

        # 加载字体文件
        font_id1 = QFontDatabase.addApplicationFont("font/pmzd.ttf")
        # 获取字体家族名称
        font_families1 = QFontDatabase.applicationFontFamilies(font_id1)
        font_family1 = font_families1[0]
        # 创建字体对象
        self.font1 = QFont(font_family1)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 321, 341))
        self.label.setStyleSheet("background-color:rgba(255, 255, 255, 240);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 126, 260, 90))
        font = QtGui.QFont(self.font1)
        font.setPointSize(33)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0,0,0,13);\n"
"    color:rgb(0, 0, 0);\n"
"    border-radius:13px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(170, 170, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/booster.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(66, 66))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 230, 260, 90))
        font = QtGui.QFont(self.font1)
        font.setPointSize(33)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0,0,0,13);\n"
"    color:rgb(0, 0, 0);\n"
"    border-radius:13px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(170, 170, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/clean.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(66, 66))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 340, 261, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 70, 261, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont(self.font)
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.hidewindow = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.hidewindow.setMinimumSize(QtCore.QSize(31, 31))
        self.hidewindow.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        self.hidewindow.setFont(font)
        self.hidewindow.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0,0,0,6);\n"
"    color:rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(170, 170, 255);\n"
"}")
        self.hidewindow.setObjectName("hidewindow")
        self.horizontalLayout.addWidget(self.hidewindow)
        self.quit = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.quit.setMinimumSize(QtCore.QSize(31, 31))
        self.quit.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.quit.setFont(font)
        self.quit.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0,0,0,6);\n"
"    color:rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 0, 0);\n"
"}")
        self.quit.setObjectName("quit")
        self.horizontalLayout.addWidget(self.quit)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.quit.clicked.connect(MainWindow.close) # type: ignore
        self.hidewindow.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "优化加速"))
        self.pushButton_2.setText(_translate("MainWindow", "深度清理"))
        self.label_3.setText(_translate("MainWindow", "Developed By DaYe\n"
"https://dyblog.netlify.app/"))
        self.label_2.setText(_translate("MainWindow", "WindowsCleaner"))
        self.hidewindow.setText(_translate("MainWindow", "-"))
        self.quit.setText(_translate("MainWindow", "X"))
