name: 编译

on:
  workflow_dispatch:
    inputs:
      sign:
        description: "代码签名"
        type: boolean
        default: false

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      sign: ${{ inputs.sign }}
